server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo?serverTimezone=UTC
    username: root
    password: root
    hikari: #数据库连接池
      aximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-server
mybatis:
  type-aliases-package: cn.lhr.demo.userserver.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 30 #服务续约(renew)的间隔，默认为30秒
    lease-expiration-duration-in-seconds: 90 #服务失效时间，默认值90秒
